name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_GITHUB_PACKAGE_PUBLICATION }}
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/projet-final:latest .
          docker tag ghcr.io/projet-final:latest ghcr.io/projet-final:$GITHUB_SHA  
          docker push ghcr.io/projet-final:latest
          docker push ghcr.io/projet-final-react:$GITHUB_SHA
